### ISSUE TITLE
gta2x1

### ISSUE THREAD

**Issue by thyagorodriguesalvarez** [UDPSendToFailed/OTA#1]
hi there, thanks for you work! im trying to install it on a sm-t590 wich seems to appear to be a gta2x1 however it does not alllow me to install as its made for gta2x1wifi, is there a way to install it on mine _+

**Comment by UDPSendToFailed** [comment]
Hi!

Try using the TWRP version from here: https://github.com/UDPSendToFailed/twrp_device_samsung_gta2xlwifi/releases/tag/3.7.0

**Comment by thyagorodriguesalvarez** [comment]
thanks :))
