### ISSUE TITLE
First Boot Shows Black Screen

### ISSUE THREAD

**Issue by 112cxyz** [UDPSendToFailed/OTA#2]
I flashed the ROM and installed magisk not done gapps yet but the device is just on a black screen. ( I have rebooted )
It's a non-LTE model

**Comment by 112cxyz** [comment]
I see the lineage os boot logo though

**Comment by 112cxyz** [comment]
I managed to bypass it by ADB shell into the device than running `am start -a android.settings.SETTINGS` then pressing back and then the setup would launch

**Comment by 112cxyz** [comment]
I keep having issues where it will just no longer boot when installing LiteGapps

**Comment by UDPSendToFailed** [comment]
Hi!

Someone in the XDA thread had the same issue, I've tried to reproduce it but haven't had any success. Could you attach the output of `adb logcat -d > logcat.txt` after a clean install? 

As for Google apps, I would recommend using [NikGApps](https://nikgapps.com/).

**Comment by 112cxyz** [comment]
[logcat after i let it boot up and run for a while ](https://github.com/UDPSendToFailed/OTA/files/10043511/logcat.4.txt)

i used scrcpy to see because it would randomly go back to "boot logo" when it was just randomly drawing it because it cant find the setup wizard i found a few interesting lines in the log as well.

**Comment by 112cxyz** [comment]
So i did more digging i found it only shows the boot logo if it hasn't completed setup for "x" amount of time but i got nikgapps setup working! but it would get stuck after selecting language and then go back to the "boot logo"

**Comment by UDPSendToFailed** [comment]
Interesting... I've checked the log and all I can see is `com.android.server.StorageManagerService` keeps crashing for some reason. 

Also got a new comment on XDA, could you try doing the same to see if it fixes the issue? Make sure you wipe the cache partition too in TWRP.

https://forum.xda-developers.com/t/rom-unofficial-13-lineageos-20-0-64-bit-for-galaxy-tab-a-10-5-2018-wifi-sm-t590.4427597/page-4#post-87745605

**Comment by 112cxyz** [comment]
I did another clean install by wiping data, reboot into recovery, formatting data, reboot again, install ota, then magisk latest, then nikgapps, it would get to setup i would select my locale and it would load forever until once again going to the boot logo

![image](https://user-images.githubusercontent.com/78795456/202846490-6e045a6a-09e3-426a-8705-265c4e8b0a8e.png)

![image](https://user-images.githubusercontent.com/78795456/202846511-e1481ff4-e668-4046-bdd2-d9af776e161a.png)

![image](https://user-images.githubusercontent.com/78795456/202846750-2ca7a879-bc89-4e18-ae2f-8dd8d3b53e7d.png)

These photos where taking using scrcpy so adb still works

**Comment by UDPSendToFailed** [comment]
Not sure if it'll change anything, but I found out from yesterday's log that you have an SD card in the tablet, could you try booting without it?

My device also had some freezing issues with SD cards, so it might be the cause of the bootloop since the crashing service is storage-related.

![image](https://user-images.githubusercontent.com/16057404/202848515-353226ad-a9ce-4d0d-8097-4df470ce4a29.png)
![image](https://user-images.githubusercontent.com/16057404/202848898-9bd03c53-608b-46c2-a20e-cdfee1d4ed13.png)

**Comment by 112cxyz** [comment]
Funny, Enough I did have a sd card inside as soon as I removed it it worked instantly! Thank you! It I think you should put it on the xda post because many people use SD cards to keep their images for reflashing. (Also what software is that it looks helpful for debugging)

**Comment by UDPSendToFailed** [comment]
Hmm... I have no idea why are SD cards causing those problems, but at least we found the cause of the bootloop. I will add that to the list of known issues.

The app is [Notepad++](https://notepad-plus-plus.org/downloads/) with the [NppLogcat](https://github.com/Laogeodritt/NppLogcat) addon.
